<?php
/**
 * Created by PhpStorm.
 * User: kibb
 * Date: 3/17/18
 * Time: 5:58 AM
 */

namespace Kibb\Exceptions;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Throwable;

class KibbNotFoundException extends ModelNotFoundException{
    public function __construct(string $message = "", int $code = 0, Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }
    
    public function getModel()
    {
        return parent::getModel(); // TODO: Change the autogenerated stub
    }
}